"""empty message

Revision ID: 782caa642daf
Revises: 
Create Date: 2019-05-22 15:38:59.819906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '782caa642daf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('events')
    op.drop_table('categories')
    op.drop_table('rsvp')
    op.drop_table('eventanalytics')
    op.drop_table('ranks')
    op.drop_table('savedevents')
    op.drop_table('ranking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranking',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ranking_pkey'),
    sa.UniqueConstraint('name', name='ranking_name_key')
    )
    op.create_table('savedevents',
    sa.Column('eid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['eid'], ['events.eid'], name='savedevents_eid_fkey'),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], name='savedevents_uid_fkey')
    )
    op.create_table('ranks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], name='ranks_uid_fkey'),
    sa.PrimaryKeyConstraint('id', name='ranks_pkey')
    )
    op.create_table('eventanalytics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('saved_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event'], ['events.eid'], name='eventanalytics_event_fkey'),
    sa.PrimaryKeyConstraint('id', name='eventanalytics_pkey')
    )
    op.create_table('rsvp',
    sa.Column('eid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['eid'], ['events.eid'], name='rsvp_eid_fkey'),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], name='rsvp_uid_fkey')
    )
    op.create_table('categories',
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name', name='categories_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('events',
    sa.Column('eid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('imageurl', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('briefdescription', sa.VARCHAR(length=240), autoincrement=False, nullable=False),
    sa.Column('fulldescription', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('starttimestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('endtimestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('place', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('categoryname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contactemail', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('contactphone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('postedby', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('postedtimestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['categoryname'], ['categories.name'], name='events_categoryname_fkey'),
    sa.ForeignKeyConstraint(['postedby'], ['users.uid'], name='events_postedby_fkey'),
    sa.PrimaryKeyConstraint('eid', name='events_pkey')
    )
    op.create_table('users',
    sa.Column('uid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('displayname', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('first', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('activated', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('dateofbirth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('datecreated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uid', name='users_pkey')
    )
    # ### end Alembic commands ###
